//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Home", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company employees implemented more than 150 000 hours of development in Microsoft Dynamics AX version 2.1 – 2012 and more than 150 successful projects;.
        /// </summary>
        internal static string companyEmployeesImplemented {
            get {
                return ResourceManager.GetString("companyEmployeesImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We consider the company mission in providing professional consulting and development in Microsoft Dynamics AX..
        /// </summary>
        internal static string companyMission {
            get {
                return ResourceManager.GetString("companyMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great experience in Axapta versions upgrade projects, upgrade of implemented additional functionality in Axapta and customer data, it includes more than 15 upgrades to Axapta 4, more than 15 upgrades to version 2009 and over 10 upgrades to version 2012..
        /// </summary>
        internal static string greatExperienceInAX {
            get {
                return ResourceManager.GetString("greatExperienceInAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great experience in remote work;.
        /// </summary>
        internal static string greatExperienceInRemote {
            get {
                return ResourceManager.GetString("greatExperienceInRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great international experience, which makes it possible to reuse successful ideas of other projects made in different countries;.
        /// </summary>
        internal static string greatInternationalExperience {
            get {
                return ResourceManager.GetString("greatInternationalExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable staff;.
        /// </summary>
        internal static string stableStaff {
            get {
                return ResourceManager.GetString("stableStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company is located in Belarus, Minsk and its staff consists of 12 professional Microsoft Dynamics AX and CRM developers..
        /// </summary>
        internal static string theCompanyIsLocated {
            get {
                return ResourceManager.GetString("theCompanyIsLocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main features of our company are as follows:.
        /// </summary>
        internal static string theMainFeatures {
            get {
                return ResourceManager.GetString("theMainFeatures", resourceCulture);
            }
        }
    }
}
