//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Home", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We at Dyna-Soft are passionate about helping people customize and extend Microsoft Dynamics products. Founded in 2021 by four partners with over twenty years of experience in Microsoft Dynamics AX development, the company consists of skilled and professional developers constantly looking for developing their skills and following best practices.
        /// </summary>
        internal static string aboutHome {
            get {
                return ResourceManager.GetString("aboutHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyna-Soft is a Microsoft Dynamics 365 and Microsoft Dynamics CE development and consulting company founded by partners with more than 20 years of ERP development. We deliver services for ERP and CRM customization and extension, as well as technical analysis and post-go-life support. Our team consists of skilled and professional developers and consultants delivering results to our customers and partners in time and with high quality. No matter what challenges our customers face, we try to help them where nee [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aboutIntro {
            get {
                return ResourceManager.GetString("aboutIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyna-Soft is a Microsoft Dynamics 365 and Microsoft Dynamics CE development and consulting company founded by partners with more than 20 years of ERP development. We deliver services for ERP and CRM customization and extension, as well as technical analysis and post-go-life support. Our team consists of skilled and professional developers and consultants delivering results to our customers and partners in time and with high quality.
        /// </summary>
        internal static string aboutMain {
            get {
                return ResourceManager.GetString("aboutMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyna-Soft Sp. z o.o..
        /// </summary>
        internal static string address1 {
            get {
                return ResourceManager.GetString("address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szpitalna str., 8, apt. 6.
        /// </summary>
        internal static string address2 {
            get {
                return ResourceManager.GetString("address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00-031 Warsaw, Poland.
        /// </summary>
        internal static string address3 {
            get {
                return ResourceManager.GetString("address3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andrew Kuzmich.
        /// </summary>
        internal static string AKU {
            get {
                return ResourceManager.GetString("AKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner, senior D365FO developer, solution architect, team and project manager. Experience in Microsoft Dynamics AX since 2000, participated in development and support of standard Axapta module “Cost accounting”. Axapta Certified Master since 2004 MORE TO ADD.
        /// </summary>
        internal static string AKUDescr {
            get {
                return ResourceManager.GetString("AKUDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliaksander Ahranovich.
        /// </summary>
        internal static string ALA {
            get {
                return ResourceManager.GetString("ALA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner, senior D365FO and CE developer, solution architect, team and project manager. Experience in Microsoft Dynamics AX since 2005. Axapta and CRM Certified Professional and Microsoft SQL Server Certified Professional since 2006 MORE TO ADD.
        /// </summary>
        internal static string ALADescr {
            get {
                return ResourceManager.GetString("ALADescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alex Kurilenko.
        /// </summary>
        internal static string ALK {
            get {
                return ResourceManager.GetString("ALK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior .NET, Retail and MS CRM developer, solution architect MORE TO ADD.
        /// </summary>
        internal static string ALKDescr {
            get {
                return ResourceManager.GetString("ALKDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alex Potonia.
        /// </summary>
        internal static string ALP {
            get {
                return ResourceManager.GetString("ALP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior D365FO developer. MORE TO ADD.
        /// </summary>
        internal static string ALPDescr {
            get {
                return ResourceManager.GetString("ALPDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andrew Truesevich.
        /// </summary>
        internal static string ANT {
            get {
                return ResourceManager.GetString("ANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior D365FO developer. MORE TO ADD.
        /// </summary>
        internal static string ANTDescr {
            get {
                return ResourceManager.GetString("ANTDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andrew Yaroslavtsev.
        /// </summary>
        internal static string ANY {
            get {
                return ResourceManager.GetString("ANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner, senior D365FO developer, solution architect, team and project manager. Experience in Microsoft Dynamics AX and Concorde XAL since 1999. Axapta Certified Master since 2004 MORE TO ADD.
        /// </summary>
        internal static string ANYDescr {
            get {
                return ResourceManager.GetString("ANYDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure based integrations.
        /// </summary>
        internal static string azureBasedIntegrations {
            get {
                return ResourceManager.GetString("azureBasedIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking.
        /// </summary>
        internal static string banking {
            get {
                return ResourceManager.GetString("banking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical industry.
        /// </summary>
        internal static string chemicalIndustry {
            get {
                return ResourceManager.GetString("chemicalIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact details for Dyna-Soft Spółka z Ograniczoną Odpowiedzialnością.
        /// </summary>
        internal static string companyContact {
            get {
                return ResourceManager.GetString("companyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We implemented more than 250 000 hours of development in Microsoft Dynamics AX version 2.1 – 2012, and Microsoft Dynamics 365 fulfilling more than 200 successful projects.
        /// </summary>
        internal static string companyEmployeesImplemented {
            get {
                return ResourceManager.GetString("companyEmployeesImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mission is providing professional consulting and development services for our partners and customers in Microsoft Dynamics 365 and CE. Our highlights are.
        /// </summary>
        internal static string companyMission {
            get {
                return ResourceManager.GetString("companyMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical audit of running ERP and CRM systems.
        /// </summary>
        internal static string completeAppraisal {
            get {
                return ResourceManager.GetString("completeAppraisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics 365 Customer Engagement (CRM) Development.
        /// </summary>
        internal static string crmDevelopment {
            get {
                return ResourceManager.GetString("crmDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics 365 Customer Engagement (CRM) Upgrade.
        /// </summary>
        internal static string crmUpgrade {
            get {
                return ResourceManager.GetString("crmUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DMF based integrations.
        /// </summary>
        internal static string DMFBasedIntegrations {
            get {
                return ResourceManager.GetString("DMFBasedIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dmitry Mikhaevich.
        /// </summary>
        internal static string DMM {
            get {
                return ResourceManager.GetString("DMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior D365FO developer, .NET developer, MORE TO ADD.
        /// </summary>
        internal static string DMMDescr {
            get {
                return ResourceManager.GetString("DMMDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dmitri Stepanov.
        /// </summary>
        internal static string DMS {
            get {
                return ResourceManager.GetString("DMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner, senior D365FO developer, solution architect, team and project manager. Experience in Microsoft Dynamics AX and Concorde XAL since 1999. Axapta Certified Master since 2004 MORE TO ADD.
        /// </summary>
        internal static string DMSDescr {
            get {
                return ResourceManager.GetString("DMSDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document workflow management.
        /// </summary>
        internal static string documentWorkflowManagement {
            get {
                return ResourceManager.GetString("documentWorkflowManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET development.
        /// </summary>
        internal static string dotNetDevelopment {
            get {
                return ResourceManager.GetString("dotNetDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual-Write integrations.
        /// </summary>
        internal static string dualWriteIntegrations {
            get {
                return ResourceManager.GetString("dualWriteIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diana Verich.
        /// </summary>
        internal static string DVE {
            get {
                return ResourceManager.GetString("DVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior D365FO developer, .NET developer, Azure integration specialist MORE TO ADD.
        /// </summary>
        internal static string DVEDescr {
            get {
                return ResourceManager.GetString("DVEDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyna-Soft.
        /// </summary>
        internal static string DynaSoft {
            get {
                return ResourceManager.GetString("DynaSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eCOM development.
        /// </summary>
        internal static string eCOMDevelopment {
            get {
                return ResourceManager.GetString("eCOMDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economic and technical consulting, projects architecture.
        /// </summary>
        internal static string ecoTechConsulting {
            get {
                return ResourceManager.GetString("ecoTechConsulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity supply.
        /// </summary>
        internal static string electricitySupply {
            get {
                return ResourceManager.GetString("electricitySupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering industry.
        /// </summary>
        internal static string engineeringIndustry {
            get {
                return ResourceManager.GetString("engineeringIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics 365 Electronic Reporting and Reporting development.
        /// </summary>
        internal static string ERandRDLDevelopment {
            get {
                return ResourceManager.GetString("ERandRDLDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields of automation.
        /// </summary>
        internal static string fieldsOfAutomation {
            get {
                return ResourceManager.GetString("fieldsOfAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food industry.
        /// </summary>
        internal static string foodIndustry {
            get {
                return ResourceManager.GetString("foodIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensive experience in Microsoft Axapta upgrade projects, upgrade of customized functionality and customer data migration resulted in more than 15 upgrades to Axapta 4, more than 15 upgrades to version 2009 and over 20 upgrades to version 2012.
        /// </summary>
        internal static string greatExperienceInAX {
            get {
                return ResourceManager.GetString("greatExperienceInAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have great experience in Microsoft Dynamics CE customization and upgrades.
        /// </summary>
        internal static string greatExperienceInCRM {
            get {
                return ResourceManager.GetString("greatExperienceInCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have great experience in extending the standard Microsoft Dynamics 365 functionality, including retail (POS) and Ecom development.
        /// </summary>
        internal static string greatExperienceInExtending {
            get {
                return ResourceManager.GetString("greatExperienceInExtending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our experience in both ERP and CRM systems allow us build very robust and predictable integrations which can be based on a variety of integration platforms, including Scribe and Dual-Write.
        /// </summary>
        internal static string greatExperienceInIntegration {
            get {
                return ResourceManager.GetString("greatExperienceInIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are focused on remote work but we also can help customers onsite.
        /// </summary>
        internal static string greatExperienceInRemote {
            get {
                return ResourceManager.GetString("greatExperienceInRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our POS and eCOM experience allow us build scalable and stable solutions for retail market and reuse our how-tos for different customers.
        /// </summary>
        internal static string greatExperiencePOSEcom {
            get {
                return ResourceManager.GetString("greatExperiencePOSEcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our great international experience makes it possible to reuse successful ideas of other projects made in different countries and across different customers.
        /// </summary>
        internal static string greatInternationalExperience {
            get {
                return ResourceManager.GetString("greatInternationalExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design, implementation and support of ERP and CRM systems integration based on various integration platforms, including Dual-Write, Scribe and custom solutions.
        /// </summary>
        internal static string integration {
            get {
                return ResourceManager.GetString("integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrations.
        /// </summary>
        internal static string integrations {
            get {
                return ResourceManager.GetString("integrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iryna Vorobieva.
        /// </summary>
        internal static string IRG {
            get {
                return ResourceManager.GetString("IRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior .NET, Retail and MS CRM developer, solution architect MORE TO ADD.
        /// </summary>
        internal static string IRGDescr {
            get {
                return ResourceManager.GetString("IRGDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julyana Kruk.
        /// </summary>
        internal static string JUK {
            get {
                return ResourceManager.GetString("JUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company and project manager MORE TO ADD.
        /// </summary>
        internal static string JUKDescr {
            get {
                return ResourceManager.GetString("JUKDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konstantin Makchrakov.
        /// </summary>
        internal static string KOM {
            get {
                return ResourceManager.GetString("KOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET, Retail and MS CRM developer. MORE TO ADD.
        /// </summary>
        internal static string KOMDescr {
            get {
                return ResourceManager.GetString("KOMDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaserNet development.
        /// </summary>
        internal static string laserNetDevelopment {
            get {
                return ResourceManager.GetString("laserNetDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light and heavy industry.
        /// </summary>
        internal static string lightAndHeavyIndustry {
            get {
                return ResourceManager.GetString("lightAndHeavyIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main customers.
        /// </summary>
        internal static string mainCustomers {
            get {
                return ResourceManager.GetString("mainCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics D365 Offline POS database optimizations.
        /// </summary>
        internal static string MPOSDBOptimization {
            get {
                return ResourceManager.GetString("MPOSDBOptimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics D365 POS and retail development.
        /// </summary>
        internal static string msposDevelopment {
            get {
                return ResourceManager.GetString("msposDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System performance optimization.
        /// </summary>
        internal static string optimPerformance {
            get {
                return ResourceManager.GetString("optimPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team.
        /// </summary>
        internal static string ourTeam {
            get {
                return ResourceManager.GetString("ourTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string phoneAbbr {
            get {
                return ResourceManager.GetString("phoneAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string phoneHelp {
            get {
                return ResourceManager.GetString("phoneHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of Sale.
        /// </summary>
        internal static string pos {
            get {
                return ResourceManager.GetString("pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerApps development.
        /// </summary>
        internal static string powerAppsDevelopment {
            get {
                return ResourceManager.GetString("powerAppsDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        internal static string production {
            get {
                return ResourceManager.GetString("production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string readMore {
            get {
                return ResourceManager.GetString("readMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        internal static string references {
            get {
                return ResourceManager.GetString("references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We at Dyna-Soft are striving to be a good and valued partner to our customers. We aim for long-term collaboration because a happy customer is our main goal leading to a win-win solution for our partners and Dyna-Soft.
        /// </summary>
        internal static string referencesHome {
            get {
                return ResourceManager.GetString("referencesHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We value our customers and deliver our services with highest quality possible which helps us become partners with our customers and leads to long-term collaboration. Our customers are located in European Union and include Sweden, Switzerland, France, Denmark, Germany, United Kingdom, as well as United States of America.
        /// </summary>
        internal static string referencesMain {
            get {
                return ResourceManager.GetString("referencesMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics 365 development and consulting.
        /// </summary>
        internal static string remoteAXDev {
            get {
                return ResourceManager.GetString("remoteAXDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics 365 Customer Engagement development and consulting.
        /// </summary>
        internal static string remoteCRMDev {
            get {
                return ResourceManager.GetString("remoteCRMDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail.
        /// </summary>
        internal static string retail {
            get {
                return ResourceManager.GetString("retail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scribe and Scribe Online integrations.
        /// </summary>
        internal static string scribeIntegrations {
            get {
                return ResourceManager.GetString("scribeIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send e-mails to.
        /// </summary>
        internal static string sendEmail {
            get {
                return ResourceManager.GetString("sendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyna-Soft is helping partners with Microsoft Dynamics 365 and Microsoft Dynamics CE customization and consulting, as well as integrations. Our services incude requirements analysis, technical audit, design, implementation and development, as well as post go-life support.
        /// </summary>
        internal static string servicesHome {
            get {
                return ResourceManager.GetString("servicesHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We at Dyna-Soft help our customers and partners with Microsoft Dynamics 365 and Microsoft Dynamics CE customization and consulting, as well as integrations. Our services incude but are not limited to.
        /// </summary>
        internal static string servicesIntro {
            get {
                return ResourceManager.GetString("servicesIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All businesses are unique and many require a proper implementation of ERP and / or CRM systems. Dyna-Soft specializes on Microsoft Dynamics 365 and CE development and consulting, including technical analysis, design, development, implementation and live system support. Our team has a big experience in Microsoft Dynamics 365 (AX), including Retail and eCOM development and customization, Microsoft Dynamics CE development and is able to implement the integrations for Dynamics systems.
        /// </summary>
        internal static string servicesMain {
            get {
                return ResourceManager.GetString("servicesMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have a very stable staff.
        /// </summary>
        internal static string stableStaff {
            get {
                return ResourceManager.GetString("stableStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company is located in Republic of Poland in Warsaw and Wrocław cities and its staff consists of 10 professional Microsoft Dynamics AX and CRM developers.
        /// </summary>
        internal static string theCompanyIsLocated {
            get {
                return ResourceManager.GetString("theCompanyIsLocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main features of our company are as follows.
        /// </summary>
        internal static string theMainFeatures {
            get {
                return ResourceManager.GetString("theMainFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics AX upgrade to versions 3.X, 4.X, 2009, 2012 and D365FO.
        /// </summary>
        internal static string upgradeAX {
            get {
                return ResourceManager.GetString("upgradeAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics CRM upgrade to versions 2011, 2013, 2015 (online or on-premise).
        /// </summary>
        internal static string upgradeCRM {
            get {
                return ResourceManager.GetString("upgradeCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        internal static string viewDetails {
            get {
                return ResourceManager.GetString("viewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vladislav Tsarik.
        /// </summary>
        internal static string VLT {
            get {
                return ResourceManager.GetString("VLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D365FO and .NET developer. MORE TO ADD.
        /// </summary>
        internal static string VLTDescr {
            get {
                return ResourceManager.GetString("VLTDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale.
        /// </summary>
        internal static string wholesale {
            get {
                return ResourceManager.GetString("wholesale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer goods wholesale.
        /// </summary>
        internal static string wholesaleOfComputers {
            get {
                return ResourceManager.GetString("wholesaleOfComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale of food.
        /// </summary>
        internal static string wholesaleOfFoods {
            get {
                return ResourceManager.GetString("wholesaleOfFoods", resourceCulture);
            }
        }
    }
}
